site_name: dbgi-object-manager
repo_url: https://github.com/digital-botanical-gardens-initiative/dbgi-object-manager
site_url: https://digital-botanical-gardens-initiative.github.io/dbgi-object-manager
site_description: A Python package top handle objects in the DBGI Directus DB and issue associated labels
site_author: Digital Botanical Gardens Initiative
edit_uri: edit/main/docs/
repo_name: digital-botanical-gardens-initiative/dbgi-object-manager
copyright: Maintained by <a href="https://digital-botanical-gardens-initiative.com">Florian</a>.

nav:
  - Home: index.md
  - Modules: modules.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
            setup_commands:
                - import sys
                - sys.path.append('../')
theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/digital-botanical-gardens-initiative/dbgi-object-manager
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/dbgi-object-manager

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
